apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        env: development
    spec:
      containers:
        - image: >-
            gcr.io/auth-app-279713/github.com/pamuditha/node-app-with-gke-deployment-yaml
          imagePullPolicy: IfNotPresent
          name: node-app-with-gke-deployment-yaml-1
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: my-app
