apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appps
  name: appps
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appps
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: appps
    spec:
      containers:
        - image: >-
            gcr.io/auth-app-279713/github.com/pamuditha/node-app-with-gke-deployment-yaml
          imagePullPolicy: IfNotPresent
          name: node-app-with-gke-deployment-yaml-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: appps
  name: appps-hpa-mcso
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appps
